// file generated by the Paraglide-Next init command
import { Navigation, Middleware, DetectionStrategy } from "@inlang/paraglide-next"
import { AvailableLanguageTag } from "./paraglide/runtime";

const strategy = DetectionStrategy<AvailableLanguageTag>();

export const paraglideMiddleware = Middleware({ strategy });
export const {
	useRouter: useRouterI18n,
	redirect: redirectI18n,
	
} = Navigation({ strategy });
