// file generated by the Paraglide-Next init command
import { Navigation, Middleware, DetectionStrategy } from "@inlang/paraglide-next"
import type { AvailableLanguageTag } from "@/features/localization/model/paraglide/runtime"

const strategy = DetectionStrategy<AvailableLanguageTag>();

export const paraglideMiddleware = Middleware({ strategy });
export const {
	useRouter
} = Navigation({ strategy });
