export const ENTITY_TAGS = {
  ITEM: 'item',
  ACHIEVEMENT: 'achievement',
  AZERITE_ESSENCE: 'azerite-essence',
  COVENANT: 'covenant',
  CREATURE_DISPLAY: 'creature-display',
  CREATURE_FAMILY: 'creature-family',
  GUILD_CREST_BORDER: 'guild-crest/border',
  GUILD_CREST_EMBLEM: 'guild-crest/emblem',
  JOURNAL_INSTANCE: 'journal-instance',
  KEYSTONE_AFFIX: 'keystone-affix',
  PET_ABILITY: 'pet-ability',
  PET: 'pet',
  PLAYABLE_CLASS: 'playable-class',
  PLAYABLE_SPECIALIZATION: 'playable-specialization',
  PROFESSION: 'profession',
  RECIPE: 'recipe',
  PVP_TIER: 'pvp-tier',
  SPELL: 'spell',
  TECH_TALENT: 'tech-talent',
	MOUNT: 'mount',
} as const
