import { LanguageProvider } from "@inlang/paraglide-next"
import { languageTag } from "@/paraglide/runtime.js"
import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import './tailwind.css'
import { Providers } from "./providers"
import { LanguageSelector } from "@/features/localization/LanguageSelector";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <LanguageProvider>
   <html lang={languageTag()} className="dark">
      <body>
        <Providers>
          <LanguageSelector />
          {children}
        </Providers>
      </body>
    </html>
 </LanguageProvider>
  );
}
